import { ServiceOrder } from "@/database/models/ServiceOrder";
import { FindOptionsRelations, FindOptionsSelect } from "typeorm";
import { EmployeeSelectBasic } from "../employee/employee.select";

export const ServiceOrderSelectBasic: FindOptionsSelect<ServiceOrder> = {
  id: true,
  customerId: true,
  branchId: true,
  code: true,
  order: {
    id: true,
    code: true,
  },
  branch: {
    id: true,
    name: true,
    code: true,
    employeeId: true,
  },
  employeeId: true,
  employee: {
    id: true,
    name: true,
    phone: true,
    zaloName: true,
    user: {
      id: true,
      username: true,
    },
  },
  branchManagerId: true,
  branchManager: EmployeeSelectBasic,
  customer: {
    id: true,
    name: true,
    phone: true,
    zaloName: true,
    user: {
      id: true,
      username: true,
    },
  },
  type: true,
  timeAt: true,
  orderStartNotificationSentAt: true,
  address: true,
  isUrgent: true,
  hasFragileItems: true,
  basePrice: true,
  vouchersId: true,
  vouchers: {
    id: true,
    code: true,
    redeemedAt: true,
    expiredAt: true,
    isUsed: true,
    usedAt: true,
    vouchersTemplate: {
      id: true,
      name: true,
      code: true,
      points: true,
      amount: true,
      status: true,
    },
  },
  preVatAmount: true,
  hasVat: true,
  vat: true,
  vatAmount: true,
  amount: true,
  status: true,
  rating: true,
  isDebt: true,
  needsQuote: true,
  documentRequirement: true,
  contactName: true,
  contactPhone: true,
  description: true,
  specialRequirements: true,
  employeeSpecialization: true,
  employeeCount: true,
  floorLocationPickup: true,
  hasElevatorPickup: true,
  floorLocationDelivery: true,
  hasElevatorDelivery: true,
  itemsDetail: true,
  needsWrapping: true,
  needsDismantle: true,
  needsCleaning: true,
  movingVehicleType: true,
  vehicleTonnage: true,
  tripCount: true,
  pickupAddress: true,
  distanceToPickup: true,
  deliveryAddress: true,
  distanceToDelivery: true,
  containerCount: true,
  containerUnit: true,
  containerWeight: true,
  containerLocationType: true,
  contSpecialRequirements: true,
  distanceToStorage: true,
  cargoUnitCount: true,
  needsForklift: true,
  forkliftCount: true,
  needsCrane: true,
  craneCount: true,
  siteType: true,
  siteArea: true,
  materialsDetail: true,
  carType: true,
  quote: true,
  createdAt: true,
  updatedAt: true,
  servicePrices: true,
};

export const ServiceOrderSelectFull: FindOptionsSelect<ServiceOrder> = {
  ...ServiceOrderSelectBasic,
};

export const ServiceOrderRelations: FindOptionsRelations<ServiceOrder> = {
  customer: {
    user: true,
  },
  branch: true,
  employee: {
    user: true,
  },
  branchManager: {
    user: true,
  },
  order: true,
  vouchers: {
    vouchersTemplate: true,
  },
};
