/**
 * gen-fe-enums.ts
 *
 * Đọc BE/src/shared/constants/constance.ts (source of truth) → sinh file
 * `FE/src/constants/enum.generated.ts` chứa tất cả enum dưới dạng
 * `as const` object + derived type. Điều này đảm bảo FE luôn đồng bộ với
 * BE enum, tránh bug "Enum.X không tồn tại → undefined" mà TS không báo
 * lỗi (vì index access trên enum trả về undefined hợp lệ kiểu enum).
 *
 * Cách dùng:
 *   cd BE
 *   npm run enum:gen         # generate / overwrite FE file
 *   npm run enum:gen:check   # CI mode: exit 1 nếu file stale
 *
 * Tại sao cần script này: xem BE/src/shared/constants/constance.ts header
 * hoặc FE/src/constants/enum.ts comment trên NotificationTypeEnum.
 */

import * as ts from "typescript";
import * as fs from "fs";
import * as path from "path";

// Resolve paths relative to repo root. BE/ and FE/ are siblings inside
// the monorepo working dir (BOC_XEP_THIEN_BAO).
const REPO_ROOT = path.resolve(__dirname, "../..");
const SOURCE = path.join(REPO_ROOT, "BE/src/shared/constants/constance.ts");
// Output vào folder `generated/` riêng để tránh confusion/conflict với
// `FE/src/constants/enum.ts` (manual). Dev import từ đây cần rename hoặc
// merge vào enum.ts theo workflow migrate (xem CLAUDE.md).
const OUTPUT = path.join(REPO_ROOT, "FE/src/constants/generated/enums.be.ts");

interface ParsedEnum {
  name: string;
  values: Record<string, string>;
}

interface ParseResult {
  enums: ParsedEnum[];
  skippedMembers: { enumName: string; memberKey: string }[];
}

/**
 * Parse tất cả `export enum` trong file TS.
 * Chỉ lấy string literal values (antd Select/Checkbox cần string).
 * Bỏ qua numeric/computed values — track lại để byte-comparison catch thay đổi.
 */
function parseEnums(filePath: string): ParseResult {
  if (!fs.existsSync(filePath)) {
    throw new Error(`[enum:gen] Source not found: ${filePath}`);
  }
  const source = fs.readFileSync(filePath, "utf-8");
  const sourceFile = ts.createSourceFile(
    filePath,
    source,
    ts.ScriptTarget.ES2020,
    /* setParentNodes */ true,
  );

  const enums: ParsedEnum[] = [];
  const skippedMembers: { enumName: string; memberKey: string }[] = [];

  function visit(node: ts.Node) {
    if (ts.isEnumDeclaration(node)) {
      const isExported = node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
      if (isExported) {
        const name = node.name.text;
        const values: Record<string, string> = {};

        for (const member of node.members) {
          if (!ts.isEnumMember(member)) continue;

          // Enum member name có thể là `Identifier` (FOO = "x") hoặc
          // `StringLiteral` ("FOO" = "x"). Cả hai đều có `.text`.
          const memberName = member.name;
          const key = ts.isIdentifier(memberName) || ts.isStringLiteral(memberName) ? memberName.text : null;
          if (!key) continue;
          const init = member.initializer;

          if (init && ts.isStringLiteral(init)) {
            values[key] = init.text;
          } else {
            // Numeric hoặc computed: bỏ qua — antd Select/Checkbox cần string.
            // Track lại để file output phản ánh thay đổi AST (byte-comparison catch).
            skippedMembers.push({ enumName: name, memberKey: key });
          }
        }

        enums.push({ name, values });
      }
    }
    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return { enums, skippedMembers };
}

/**
 * Generate file content: header + mỗi enum là `as const` object + type alias.
 *
 * QUAN TRỌNG — scope sử dụng:
 * - File này KHÔNG nên import tự động ở FE code (sẽ trùng tên với
 *   `FE/src/constants/enum.ts` cho các enum chung như NotificationTypeEnum,
 *   FileTypeEnum, FinanceTypeEnum...).
 * - Hiện tại file này là output dạng "diff để review". Dev chạy `enum:gen`
 *   → diff file này → nếu hợp lý, copy từng enum cần sync sang
 *   `FE/src/constants/enum.ts` (hoặc migrate code dùng enum đó sang
 *   import từ file generated).
 * - Lộ trình tương lai: migrate dần `FE/src/constants/enum.ts` để
 *   `export * from "./enum.generated"` cho các enum BE-owned, giữ
 *   các enum FE-only (SortTypeEnum, GenderEnum, ...) ở enum.ts.
 */
function generateCode(result: ParseResult): string {
  const { enums, skippedMembers } = result;

  // Build skipped summary cho header — byte-comparison sẽ catch mọi thay đổi.
  const skippedSummary =
    skippedMembers.length === 0
      ? "none"
      : skippedMembers.map((s) => `${s.enumName}.${s.memberKey}`).join(", ");

  const header = `/**
 * AUTO-GENERATED by BE/scripts/gen-fe-enums.ts
 * Source: BE/src/shared/constants/constance.ts
 *
 * KHÔNG SỬA FILE NÀY THỦ CÔNG — sẽ bị overwrite khi chạy \`npm run enum:gen\`.
 * Để thêm/sửa enum: sửa ở BE/src/shared/constants/constance.ts, sau đó chạy
 * \`cd BE && npm run enum:gen\`.
 *
 * Tại sao file này tồn tại: TS không phát hiện được khi FE truy cập
 * \`SomeEnum.MISSING_VALUE\` (index access trên enum trả về undefined hợp lệ).
 * Điều này gây crash runtime trong antd Checkbox.Group / Select / Radio.Group
 * (chúng gọi .toString() trên undefined). Auto-sync BE→FE enum loại bỏ
 * class bug này tại build time.
 *
 * CI check: \`cd BE && npm run enum:gen:check\` — exit 1 nếu file stale.
 *
 * Skipped non-string members: ${skippedSummary}
 *
 * ⚠️  SCOPE — CHƯA WIRING:
 * File này được tạo tự động nhưng KHÔNG nên import tự động ở FE code.
 * Xem comment trong BE/scripts/gen-fe-enums.ts để biết workflow migrate.
 */

`;

  const body = enums
    .map(({ name, values }) => {
      const objEntries = Object.entries(values)
        .map(([k, v]) => `  ${k}: "${v}",`)
        .join("\n");
      return `export const ${name} = {
${objEntries}
} as const;

export type ${name} = (typeof ${name})[keyof typeof ${name}];
`;
    })
    .join("\n");

  return header + body.trimEnd() + "\n";
}

function main(): void {
  const result = parseEnums(SOURCE);
  if (result.enums.length === 0) {
    console.error(`[enum:gen] No exported enums found in ${SOURCE}`);
    process.exit(1);
  }

  // Log skip warnings lên console (stderr) — không ảnh hưởng file output.
  for (const s of result.skippedMembers) {
    console.warn(`[enum:gen] Skip non-string value: ${s.enumName}.${s.memberKey}`);
  }

  const generated = generateCode(result);
  const checkMode = process.argv.includes("--check");

  if (checkMode) {
    const existing = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, "utf-8") : "";
    if (existing !== generated) {
      console.error(`[enum:gen] STALE: ${OUTPUT}`);
      console.error(`  Fix: cd BE && npm run enum:gen`);
      process.exit(1);
    }
    console.log(
      `[enum:gen] OK — ${result.enums.length} enums (${result.skippedMembers.length} skipped) up-to-date at ${OUTPUT}`,
    );
    return;
  }

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, generated);
  console.log(
    `[enum:gen] Wrote ${result.enums.length} enums (${result.skippedMembers.length} skipped) to ${OUTPUT}`,
  );
}

main();
